package main

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"
	"unicode"
	// "fmt"
	// "io"
	"os"
	// "path/filepath"
)
type JsonObject map[string]any
func main(){
	path, _ := os.Getwd()
	fullpath := path + "/example.json"
	file := ReadJson(fullpath)
	CreateStruct(file)
}
func check(e error) {
    if e != nil {
        panic(e)
    }
}
func ReadJson(path string) JsonObject {
	file, error := os.ReadFile(path)
	check(error)
	var data map[string]any
	error = json.Unmarshal(file, &data)
	check(error)
	return JsonObject(data)
}
func getType(v any) string {
	switch val := v.(type) {
	case string:
		return "string"
	case float64:
		if float64(int(val)) == val {
            return "int"
        }
		return "float64"
	case bool:
		return "bool"
	case map[string]any:
		return generateInlineStruct(val);
	case []any:
		return detectSliceType(val);
	default:
		return "any"
	}
}
func detectSliceType(slice []any) string{
	if len(slice) == 0 {
		return "[]any"
	}
	firstType := getType(slice[0])
	for _, item := range slice {
		if getType(item) != firstType {
			fmt.Println("Warning: This slice is consisting of mixed types -> ",slice)
			return "[]any"
		}
	}
	return "[]" + firstType
}
func toPascalCase(s string) string {
    if strings.ContainsAny(s, "_-") {
        s = strings.ReplaceAll(s, "-", " ")
        s = strings.ReplaceAll(s, "_", " ")
        words := strings.Fields(s)
        for i, w := range words {
            runes := []rune(w)
            runes[0] = unicode.ToUpper(runes[0])
            words[i] = string(runes)
        }
        return strings.Join(words, "")
    }
    if len(s) > 0 {
        runes := []rune(s)
        runes[0] = unicode.ToUpper(runes[0])
        return string(runes)
    }

    return s
}
func generateInlineStruct(jsonObject JsonObject) string{
	var sb strings.Builder
	sb.WriteString("struct {\n\t")
	keys := make([]string,0,len(jsonObject))
	for k := range jsonObject {
		keys = append(keys,k)
	}
	sort.Strings(keys)

	for _ , k := range keys {
		val := jsonObject[k]
		fieldName := toPascalCase(k)
		fieldValue := getType(val)
		sb.WriteString(fmt.Sprintf("\t%s %s `json:%q`\n",fieldName,fieldValue,k))
	}
	sb.WriteString("\t}")
	return sb.String()
}
func CreateStruct(jsonObject JsonObject){
	var sb strings.Builder
	sb.WriteString("package main \n\n")
	sb.WriteString("type AutoGenerated struct {\n\t")
	for key, value := range jsonObject {
		goType := getType(value)
		fieldName := toPascalCase(key)
		line := fmt.Sprintf("\t\t%s %s `json:%q`\n",fieldName,goType,key)
		sb.WriteString(line)
	}
	sb.WriteString("}\n")
	err := os.WriteFile("model.go", []byte(sb.String()),0644)
	check(err)
	fmt.Println("Success! Generated model.go")
}