package main 

type AutoGenerated struct {
	Person struct {
	Birthday string `json:"Birthday"`
	Birthtime string `json:"Birthtime"`
	FavColor string `json:"favColor"`
	FavNumber string `json:"favNumber"`
	Name string `json:"name"`
	Surname string `json:"surname"`
	} `json:"person"`
}
